<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CommerceCore.Application</AssemblyName>
    <RootNamespace>CommerceCore.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../SharedKernel/CommerceCore.SharedKernel/CommerceCore.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
